# parameters for the baseline RandomActionAgent

training_kwargs:
  num_episodes: 10
  save_path: '/mnt/results/random_agent' # for phoebe, should begin with '/mnt'

env_kwargs:
  multimodal: True
  max_timesteps: 500
  obs_delay: 0.1
  not_moving_timeout: 50
  reward_pol: 'default'
  reward_kwargs:
    oob_penalty: 5.0
    min_oob_penalty: 25.0
  controller_kwargs:
    sim_version: 'ArrivalSim-linux-0.7.0-cmu4'
    quiet: False
    start_container: False 
    sim_path: '/home/arrival-sim/ArrivalSim-linux-0.3.0.137341-roborace/LinuxNoEditor' # '/home/jimmy/Jimmy/roborace/simulator/arrival/ArrivalSim-linux-0.3.0.137341-roborace/LinuxNoEditor'
    user: 'ubuntu' # 'jimmy'
  action_if_kwargs:
    max_accel: 6.
    min_accel: 3.
    max_steer: 0.2
    min_steer: -0.2
    ip: '0.0.0.0'
    port: 7077
  pose_if_kwargs:
    ip: '0.0.0.0'
    port: 7078
  camera_if_kwargs:
    ip: 'tcp://127.0.0.1'
    port: 8008
  segm_if_kwargs:
    ip: 'tcp://127.0.0.1'
    port: 8009
  birdseye_if_kwargs:
    ip: 'tcp://127.0.0.1'
    port: 8010
  birdseye_segm_if_kwargs:
    ip: 'tcp://127.0.0.1'
    port: 8011

sim_kwargs:
  racetrack: 'Thruxton' # ['VegasNorthRoad', 'Thruxton']
  active_sensors:
    - CameraFrontRGB
    - CameraFrontSegm
    - CameraBirdsEye
    - CameraBirdsEyeSegm
  driver_params:
    DriverAPIClass: 'VApiUdp'
    DriverAPI_UDP_SendAddress: '0.0.0.0'
  camera_params:
    Format: ColorBGR8
    FOVAngle: 90
    Width: 512
    Height: 384
    bAutoAdvertise: True
  segm_params:
    Format: SegmBGR8
    FOVAngle: 90
    Width: 512
    Height: 384
    bAutoAdvertise: True
  birdseye_params:
    Format: HdrRGB8
    FOVAngle: 90
    Width: 512
    Height: 384
    bAutoAdvertise: True
  birdseye_segm_params:
    Format: SegmBGR8
    FOVAngle: 90
    Width: 512
    Height: 384
    bAutoAdvertise: True
